// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ActivityForm: typeof import("./components/ActivityForm/ActivityForm.vue")["default"];
    ActivityList: typeof import("./components/ActivityList/ActivityList.vue")["default"];
    BackButton: typeof import("./components/BackButton/BackButton.vue")["default"];
    Button: typeof import("./components/Button/Button.vue")["default"];
    Dropdown: typeof import("./components/Dropdown/Dropdown.vue")["default"];
    DuplicateActivities: typeof import("./components/DuplicateActivities/DuplicateActivities.vue")["default"];
    ErrorBanner: typeof import("./components/ErrorBanner/ErrorBanner.vue")["default"];
    Flow: typeof import("./components/Flow/Flow.vue")["default"];
    Footer: typeof import("./components/Footer/Footer.vue")["default"];
    GlobalLoading: typeof import("./components/GlobalLoading/GlobalLoading.vue")["default"];
    Header: typeof import("./components/Header/Header.vue")["default"];
    Icon: typeof import("./components/Icons/Icon.vue")["default"];
    ImageLoader: typeof import("./components/ImageLoader/ImageLoader.vue")["default"];
    Input: typeof import("./components/Input/Input.vue")["default"];
    Item: typeof import("./components/Item/Item.vue")["default"];
    Link: typeof import("./components/Link/Link.vue")["default"];
    Loading: typeof import("./components/Loading/Loading.vue")["default"];
    Modal: typeof import("./components/Modal/Modal.vue")["default"];
    NotificationItem: typeof import("./components/NotificationItem/NotificationItem.vue")["default"];
    PlaceholderCard: typeof import("./components/Placeholder/PlaceholderCard.vue")["default"];
    PlaceholderList: typeof import("./components/Placeholder/PlaceholderList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SessionForm: typeof import("./components/SessionForm/SessionForm.vue")["default"];
    Switch: typeof import("./components/Switch/Switch.vue")["default"];
    TimePicker: typeof import("./components/TimePicker/TimePicker.vue")["default"];
    TimerSpinner: typeof import("./components/TimerSpinner/TimerSpinner.vue")["default"];
    TimeSelector: typeof import("./components/TimeSelector/TimeSelector.vue")["default"];
  }
}
