// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ActivityForm: typeof import("./components/Organisms/ActivityForm/ActivityForm.vue")["default"];
    ActivityList: typeof import("./components/Organisms/ActivityList/ActivityList.vue")["default"];
    BackButton: typeof import("./components/Molecules/BackButton/BackButton.vue")["default"];
    Banner: typeof import("./components/Atoms/Banner/Banner.vue")["default"];
    Button: typeof import("./components/Atoms/Button/Button.vue")["default"];
    Calendar: typeof import("./components/Organisms/Calendar/Calendar.vue")["default"];
    Card: typeof import("./components/Atoms/Card/Card.vue")["default"];
    CookieBanner: typeof import("./components/Organisms/CookieBanner/CookieBanner.vue")["default"];
    Dropdown: typeof import("./components/Molecules/Dropdown/Dropdown.vue")["default"];
    DuplicateActivities: typeof import("./components/Organisms/DuplicateActivities/DuplicateActivities.vue")["default"];
    ErrorBanner: typeof import("./components/Molecules/ErrorBanner/ErrorBanner.vue")["default"];
    Flow: typeof import("./components/Organisms/Flow/Flow.vue")["default"];
    Footer: typeof import("./components/Molecules/Footer/Footer.vue")["default"];
    GlobalLoading: typeof import("./components/Organisms/GlobalLoading/GlobalLoading.vue")["default"];
    Header: typeof import("./components/Molecules/Header/Header.vue")["default"];
    Icon: typeof import("./components/Atoms/Icons/Icon.vue")["default"];
    ImageLoader: typeof import("./components/Molecules/ImageLoader/ImageLoader.vue")["default"];
    Input: typeof import("./components/Atoms/Input/Input.vue")["default"];
    Item: typeof import("./components/Atoms/Item/Item.vue")["default"];
    Link: typeof import("./components/Atoms/Link/Link.vue")["default"];
    Loading: typeof import("./components/Atoms/Loading/Loading.vue")["default"];
    Modal: typeof import("./components/Molecules/Modal/Modal.vue")["default"];
    Offline: typeof import("./components/Molecules/Offline/Offline.vue")["default"];
    PlaceholderCard: typeof import("./components/Atoms/Placeholder/PlaceholderCard.vue")["default"];
    PlaceholderList: typeof import("./components/Atoms/Placeholder/PlaceholderList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SessionForm: typeof import("./components/Organisms/SessionForm/SessionForm.vue")["default"];
    Switch: typeof import("./components/Atoms/Switch/Switch.vue")["default"];
    TimePicker: typeof import("./components/Molecules/TimePicker/TimePicker.vue")["default"];
    TimerSpinner: typeof import("./components/Molecules/TimerSpinner/TimerSpinner.vue")["default"];
    TimeSelector: typeof import("./components/Molecules/TimeSelector/TimeSelector.vue")["default"];
  }
}
